CREATE TABLE IF NOT EXISTS seckill_goods (
    goods_id BIGINT PRIMARY KEY,
    stock INT NOT NULL,
    per_user_limit INT NOT NULL
);

CREATE TABLE IF NOT EXISTS seckill_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    goods_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_order_request_id UNIQUE (request_id)
);

